### PR TITLE
fix: full offline model retrieval (from cache)

### LINKED ISSUE #30: Offline models
Following the version 3 changes, I can no longer run the program while my machine is offliine (even though the model is cached, the crate still looks to perform a check against the hosted model). Could this be changed so that, if the machine is offline, it will default to the cached model?

thread 'main' panicked at src\embedding\mod.rs:127:6:
Can't load model: request error: https://huggingface.co/api/models/Qdrant/all-MiniLM-L6-v2-onnx/revision/main: Dns Failed: resolve dns name 'huggingface.co:443': No such host is known. (os error 11001)

Caused by:
    0: https://huggingface.co/api/models/Qdrant/all-MiniLM-L6-v2-onnx/revision/main: Dns Failed: resolve dns name 'huggingface.co:443': No such host is known. (os error 11001)
    1: No such host is known. (os error 11001)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### PR DESCRIPTION
**Pull request by jcorrie**
This fixes #30. Previously, an attempt to access a model while offline would fail, even if that model was already cached. This is because a request was made to the remote hugging face repo to obtain the file path of the .onnx model. This change implements a fallback search over the cache dir to find the relevant model file. It there are multiple snapshots for a particular model, it would not know which is the 'correct' file - this is unlikely to be a significant problem as this is only intended to be a fallback for DX purposes.

Also exposes new public function "get_model_info" - this is primarily to give users a convenient way of accessing model dimensions.

### CODE REVIEW

**Comment by Anush008** [comment]
Hi @jcorrie. This is fantastic.
I'm trying it out now.

File: src/lib.rs [hunk 1]
```diff
@@ -155,26 +156,33 @@ impl TextEmbedding {
...
+        let model_file_info_result = model_repo.info();
 
-        let model_file = model_repo.get(&model_file.rfilename)?;
+        // If the attempt fails (likely no connection), fall back on cached onnx file
+        let model_file_reference = match model_file_info_result {
+            std::result::Result::Ok(info) => {
+                TextEmbedding::retrieve_remote_model_file(info, &model_repo)
+            }
+            Err(ref e) => {
+                eprintln!("Error retrieving model info (likely no connection): {}", e);
```
Comment (Anush008) [inline src/lib.rs:173]: Probably remove this line.
The error message looks something like
```console
Error retrieving model info (likely no connection): request error: https://huggingface.co/api/models/Qdrant/bge-small-en-v1.5-onnx-Q/revision/main: Dns Failed: resolve dns name 'huggingface.co:443': failed to lookup address information: nodename nor servname provided, or not known
```

Which appears like something terrible happened. When instead it was properly handled.

Comment (jcorrie) [reply src/lib.rs:173]: Will do! Thanks

File: src/lib.rs [hunk 2]
```diff
@@ -421,6 +460,28 @@ fn get_embeddings(data: &[f32], dimensions: &[usize]) -> Vec<Embedding> {
     embeddings
 }
 
+/// Get the cached onnx file from the model directory
+fn get_cached_onnx_file(model: ModelInfo, cache_dir: &PathBuf) -> Option<PathBuf> {
```
Comment (Anush008) [inline src/lib.rs:464]: If I'm not mistaken, we could achieve something similar using `std::fs::read_dir` recursively instead of depending on `WalkDir`.

Comment (jcorrie) [reply src/lib.rs:464]: I think you're right - I'll take a look at switching this over

Comment (jcorrie) [reply src/lib.rs:463]: Sorry for being slow - I've just pushed this change.

**Comment by Anush008** [comment]
Thanks @jcorrie.
