### PR TITLE
fix!: Throws an informative error upon inappropriate batch size with Dynamic Quantized models

### LINKED ISSUE #107: Dynamic Quantization causes batching to change the output values
### Symptoms

The 6 quantized models in this crate

- Alibaba-NLP/gte-base-en-v1.5
- Alibaba-NLP/gte-large-en-v1.5
- mixedbread-ai/mxbai-embed-large-v1
- nomic-ai/nomic-embed-text-v1.5
- Xenova/all-MiniLM-L12-v2
- Xenova/all-MiniLM-L6-v2

(basically any `ModelInfo { model_file: "model_quantized.onnx" }`)

will produce different embeddings as the batch size changes.

### To Reproduce

Run

```sh
cargo test tests::test_embeddings -- --nocapture
```

The test should pass.

Change [batch size](https://github.com/Anush008/fastembed-rs/blob/befdb3263860e4ac3bbb87ccb55402c372aca3ef/src/tests.rs#L112) in the unit test to `Some(3)`.

Assertions should fail on the above 6 models:

```
Mismatched embeddings for model Alibaba-NLP/gte-base-en-v1.5 at index 0: -1.6916804 != -1.7032102
Mismatched embeddings for model Alibaba-NLP/gte-base-en-v1.5 at index 1: -1.7150338 != -1.7076654
Mismatched embeddings for model Alibaba-NLP/gte-base-en-v1.5 at index 2: -1.732108 != -1.729326
Mismatched embeddings for model Alibaba-NLP/gte-base-en-v1.5 at index 3: -1.530315 != -1.5317788
Mismatched embeddings for model Alibaba-NLP/gte-base-en-v1.5: ["Hello, World!", "This is an example passage.", "fastembed-rs is licensed under Apache-2.0", "Some other short text here blah blah blah"]
Mismatched embeddings for model Alibaba-NLP/gte-large-en-v1.5 at index 0: -1.6144238 != -1.6044945
Mismatched embeddings for model Alibaba-NLP/gte-large-en-v1.5 at index 1: -1.6605772 != -1.6469251
Mismatched embeddings for model Alibaba-NLP/gte-large-en-v1.5 at index 2: -1.6774151 != -1.6828246
Mismatched embeddings for model Alibaba-NLP/gte-large-en-v1.5 at index 3: -1.6387382 != -1.6265479
Mismatched embeddings for model Alibaba-NLP/gte-large-en-v1.5: ["Hello, World!", "This is an example passage.", "fastembed-rs is licensed under Apache-2.0", "Some other short text here blah blah blah"]
Mismatched embeddings for model mixedbread-ai/mxbai-embed-large-v1 at index 0: -0.21646263 != -0.1811538
Mismatched embeddings for model mixedbread-ai/mxbai-embed-large-v1 at index 1: -0.2818942 != -0.2884392
Mismatched embeddings for model mixedbread-ai/mxbai-embed-large-v1 at index 2: -0.15454057 != -0.1636593
Mismatched embeddings for model mixedbread-ai/mxbai-embed-large-v1 at index 3: -0.21518138 != -0.21548103
Mismatched embeddings for model mixedbread-ai/mxbai-embed-large-v1: ["Hello, World!", "This is an example passage.", "fastembed-rs is licensed under Apache-2.0", "Some other short text here blah blah blah"]
Mismatched embeddings for model nomic-ai/nomic-embed-text-v1.5 at index 0: 0.20303695 != 0.20999804
Mismatched embeddings for model nomic-ai/nomic-embed-text-v1.5 at index 1: 0.14249149 != 0.13103808
Mismatched embeddings for model nomic-ai/nomic-embed-text-v1.5 at index 2: 0.13759416 != 0.14427708
Mismatched embeddings for model nomic-ai/nomic-embed-text-v1.5 at index 3: 0.14991708 != 0.13452803
Mismatched embeddings for model nomic-ai/nomic-embed-text-v1.5: ["Hello, World!", "This is an example passage.", "fastembed-rs is licensed under Apache-2.0", "Some other short text here blah blah blah"]
Mismatched embeddings for model Xenova/all-MiniLM-L12-v2 at index 0: -0.078739226 != -0.07808663
Mismatched embeddings for model Xenova/all-MiniLM-L12-v2 at index 1: 0.3097751 != 0.27919534
Mismatched embeddings for model Xenova/all-MiniLM-L12-v2 at index 2: -0.051262308 != -0.0770612
Mismatched embeddings for model Xenova/all-MiniLM-L12-v2 at index 3: -0.5380101 != -0.75660324
Mismatched embeddings for model Xenova/all-MiniLM-L12-v2: ["Hello, World!", "This is an example passage.", "fastembed-rs is licensed under Apache-2.0", "Some other short text here blah blah blah"]
Mismatched embeddings for model Xenova/all-MiniLM-L6-v2 at index 0: 0.56476647 != 0.5677276
Mismatched embeddings for model Xenova/all-MiniLM-L6-v2 at index 1: 0.35537243 != 0.40180072
Mismatched embeddings for model Xenova/all-MiniLM-L6-v2 at index 2: -0.1562563 != -0.15454668
Mismatched embeddings for model Xenova/all-MiniLM-L6-v2 at index 3: -0.49482125 != -0.4672576
Mismatched embeddings for model Xenova/all-MiniLM-L6-v2: ["Hello, World!", "This is an example passage.", "fastembed-rs is licensed under Apache-2.0", "Some other short text here blah blah blah"]
```

### Cause

This is a known behaviour of Quantized model due to [dynamic quantization](https://pytorch.org/tutorials/recipes/recipes/dynamic_quantization.html):

> *quote from PyTorch*
> The key idea with dynamic quantization as described here is that we are going to determine the scale factor for activations dynamically based on the data range observed at runtime.

This means that the data range will be observed within each batch. This makes the embeddings generated incomparable across batches.

### Proposed Solution

I am currently researching this to see if we have any ways of defining the data range independent of the input data. I will also need to look deeper into how other packages deal with this.

However it is worth noting that even if we solve this issue, fundamentally any embeddings generated for a set of documents will not be comparable to embeddings for another set of documents. Embeddings from a quantized model is only of meaning when used within itself. So there is certainly an argument to say that batching naturally do not go well with quantized models, and we may just disable it when dynamic quantization is in use.

### PR DESCRIPTION
**Pull request by denwong47**
## Motivation

Closes #107, at least as the short term solution.

`EmbeddingModel` now has a `get_quantization_mode` method which will return static values for the models behaviour. Not all quantized models are affected, thus we need to tell apart the non-quantized, static quantized and dynamic quantized.

Batch size will then be checked upon `transform` to see if the batch size is appropriate; if not, returns an `Err` stating the reason for it.

Also contains a minor refactor of `text_embedding.rs`, bringing the `models_list` into static scope, not requiring repeated instantiation every time `models_list` is called. This is done via `std::sync::OnceLock`. Also provides a convenient function `get_model_info`, which is an `O(1)` lookup with no memory cost to get the correct model if exists.

## Test Plan

`cargo test --features=optimum-cli`.

The `test_embeddings` test had been split into two via a `macro_rules`, one for `None` batch size and the other for `Some(3)`. Internally `test_embeddings` will check if the batch size is appropriate, and expects an `Err` instead. For non-quantized and static quantized models, the pre-calculated embeddings sum still need to be satisfied with or without batch size.

## Breaking changes

`quantization` parameter had been added to `UserDefinedEmbeddingModel`, which cannot otherwise be inferred.

### CODE REVIEW

File: src/models/text_embedding.rs [hunk 1]
```diff
@@ -2,7 +2,14 @@ use crate::pooling::Pooling;
 
 use super::model_info::ModelInfo;
 
-#[derive(Debug, Clone, PartialEq, Eq)]
+use super::quantization::QuantizationMode;
+
+use std::{collections::HashMap, sync::OnceLock};
+
+/// Lazy static list of all available models.
+static MODEL_MAP: OnceLock<HashMap<EmbeddingModel, ModelInfo<EmbeddingModel>>> = OnceLock::new();
```
Comment (Anush008) [inline src/models/text_embedding.rs:10]: 🫡

**Review by Anush008 — APPROVED** [review]
Thank you @denwong47
